---
# tasks file for mattermost
- name: apply nginx template
  template:
    src: mattermost.conf.j2
    dest: /etc/nginx/conf.d/mattermost.conf
    
- name: config.json template
  template:
    src: config.yaml.j2
    dest: /tmp/config.yaml

- name: convert config.yaml to config.json
  command: "python -c 'import sys, yaml, json; json.dump(yaml.load(sys.stdin), sys.stdout, indent=4)' < /tmp/config.yaml > /opt/mattermost/config/config.json"
  when: overwrite_config_file








# vim:ft=ansible:
